[package]
version = "0.1.0"
name = "shared"
repository = "https://github.com/stvsmth/andika"
authors = ["Steve Smith <stvsmth@gmail.com>"]
description = "Automatic speech translation, with human support"
categories = ["Web programming"]
license = "MIT"
readme = "../README.md"
edition = "2021"
